# Parameters:
#   BucketName:
#     Type: String
#     Description: Name for S3 bucket 



Resources:
  s3-lnd-dev01:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      # BucketName: !Ref BucketName
      BucketName: "s3-lnd-dev01"
      ObjectLockEnabled: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: 'BucketOwnerPreferred'
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: Environment
          Value: Production
      VersioningConfiguration: 
        Status: 'Suspended'
